### ISSUE TITLE
how far along is this?

### ISSUE THREAD

**Issue by chessai** [andrewthad/influxdb-line-protocol#1]
does it work?

**Comment by andrewthad** [comment]
It works. It's not well documented yet. Currently, the only way to build `Tags` or `Fields` is if you already know exactly which ones will be present. This is not a limitation of the design. It should be possible to write a function with this type signature:

    data TagList = TagListCons !TagKey !TagValue | TagListNil
    tags :: TagList -> Tags

This would mean that we're going from `TagList` to `Tags` to `ByteArray`. This is a little inefficient since we could just go straight from `TagList` to `ByteArray`. Maybe it would be possible to instead provide the user a way to build a `Tags` of arbitrary length directly so that they never needed to build a `TagList`. Maybe a `TagsBuilder` would be possible:

    data TagsBuilder :: Type -> Type where
      TagsBuilder ::
           Int -- offset
        -> Int -- remaining length
        -> MutableUnliftedArray s TagKey -- keys
        -> MutableUnliftedArray s TagValue -- values
        -> TagsBuilder s
    -- Unchecked invariant: TagsBuilder is used linearly.
    newTagsBuilder :: ST s (TagsBuilder s)
    consTagsBuilder :: TagsBuilder s -> TagKey -> TagValue -> ST s (TagsBuilder s)
    unsafeFreezeTagsBuilder :: TagsBuilder s -> ST s Tags

Or we could have both so that users can choose how if they prefer speed or convenience and safety (safety here meaning "not having to worry about linearity invariants that the type system does not check).

**Comment by chessai** [comment]
question answered
